apiVersion: v1 
kind: ReplicationController
metadata:  
  name: nginx
spec:
  replicas: 2
  selector:
  project: b300111671
  service: web 
  version: "0.1" 
  template:   
  metadata:   
  name: nginx
  labels: 
  project: b300111671 
  service: web
  version: "0.1"
spec:
  containers:  
- name: nginx     
  image: nginx  
  ports:    
- containerPort: 80
