version: '3.3'
  
services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: etudiants
       MYSQL_USER: etudiants
       MYSQL_PASSWORD: etudiants_1

   wordpress:
     depends_on:
       - db
     image: wordpress:5.1.1
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: etudiants
       WORDPRESS_DB_PASSWORD: etudiants_1
       WORDPRESS_DB_NAME: etudiants
