apiVersion: apps/v1
kind: Deployment
metadata:
  name: porter-layer2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: porter-layer2
  template:
    metadata:
      labels:
        app: porter-layer2
    spec:
      containers:
        - image: luksa/kubia
          name: kubia
          ports:
            - containerPort: 8080
